#!/bin/bash

## This script is executed when the container starts up


if [ "$KICK_APACHE_WWW_ROOT" == "" ]
then
    KICK_APACHE_WWW_ROOT=/opt/www
fi
echo "Apache www-root: $KICK_APACHE_WWW_ROOT";
rm -R /var/www/html
ln -s $KICK_APACHE_WWW_ROOT /var/www/html

export APACHE_CONF_DIR_OPTIONS=""

export APACHE_ERROR_LOG="/var/log/apache2/error.log";

if [ "$SYSLOG_HOST" != "" ]
then

    export APACHE_ERROR_LOG="\"||/usr/bin/logger -d --rfc3164 -n $SYSLOG_HOST -P 4200 -p 2\"";
fi


if [ "$KICK_APACHE_FALLBACK_RESOURCE" != "" ]
then
    export APACHE_CONF_DIR_OPTIONS="FallbackResource $KICK_APACHE_FALLBACK_RESOURCE";
fi

# Write config file:
envsubst < /kickstart/flavor/000-default.conf > /etc/apache2/sites-available/000-default.conf




echo "Setting HTTP_PORT to $KICK_HTTP_PORT"
echo "Listen $KICK_HTTP_PORT" > /etc/apache2/ports.conf

iniFile="/etc/php/7.2/mods-available/kickstart-flavor.ini"
echo "; Autogenerated file by kickstart-flavor-gaia : flavor-start.sh" > $iniFile
phpenmod kickstart-flavor


XdebugIniFile="/etc/php/7.2/mods-available/xdebug.ini"
bashrc_kickstart="/home/user/.bashrc.kickstart";


if [[ "$DEV_MODE" = "0" ]]
then
    ### PRODUCTION SETTINGS ###
    echo "Setting production settings... ($iniFile)";
    echo "display_errors = no" >> $iniFile

    echo "Deactivating xdebug..."
    echo "" > $XdebugIniFile
else
    ### DEVELOPMENT SETTINGS ###
    echo "Setting development settings... ($iniFile)";
    echo "display_errors = yes" >> $iniFile
    echo "display_startup_errors = yes" >> $iniFile
    echo "zend.assertions = 1" >> $iniFile
    echo "assert.exception = 1" >> $iniFile

    echo "Activating xdebug with remote ip: $DOCKER_HOST_IP:9000..."
    cp /kickstart/flavor/xdebug.ini $XdebugIniFile

    echo 'export PHP_IDE_CONFIG="serverName=$DEV_CONTAINER_NAME"' >> $bashrc_kickstart
    echo 'export XDEBUG_CONFIG="idekey=$DEV_CONTAINER_NAME"' >> $bashrc_kickstart

    # Kickstart.sh will provide the fist ip
    echo "" >> $XdebugIniFile
    echo "xdebug.remote_host = $DOCKER_HOST_IP" >> $XdebugIniFile
    echo "xdebug.idekey = '$DEV_CONTAINER_NAME'" >> $XdebugIniFile

fi;


