name: build-latest-weekly


# Build once per week on Wednesdays 03:00
on:
  schedule:
      # * is a special character in YAML so you have to quote this string
      - cron:  '0 4 3 * *'

jobs:
  build:
    branches:
      - master
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Build the container
      run: "cd test && ./build.sh"
    - name: run tests
      run: "cd test && ./test.sh"
    - name: Trigger testing run
      run: "curl -X POST --data '{\"docker_tag\": \"latest\"}' ${{ secrets.DAILY_DOCKERHUB_PULL_URL }}"
