name: test-on-push

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Run a one-line script
      run:
        - "cd test/01-devmode"
        - "./build.sh"
        - "./test.sh"
 
